graph TB
    subgraph "Deployment Targets"
        subgraph "AWS Deployment"
            AWS_VPC[AWS VPC<br/>Public/Private Subnets]
            AWS_K8s[EKS Cluster<br/>Kubernetes]
            AWS_LB[Application Load Balancer]
            AWS_Storage[S3, EBS, EFS]
        end
        
        subgraph "GCP Deployment"
            GCP_VPC[GCP VPC<br/>Subnets]
            GCP_K8s[GKE Cluster<br/>Kubernetes]
            GCP_LB[HTTPS Load Balancer]
            GCP_Storage[Cloud Storage, Persistent Disk, Filestore]
        end
        
        subgraph "Azure Deployment"
            Azure_VNet[Azure Virtual Network<br/>Subnets]
            Azure_K8s[AKS Cluster<br/>Kubernetes]
            Azure_LB[Application Gateway]
            Azure_Storage[Blob Storage, Managed Disks, Files]
        end
        
        subgraph "Alibaba Cloud Deployment"
            Alibaba_VPC[Alibaba VPC<br/>VSwitches]
            Alibaba_K8s[ACK Cluster<br/>Kubernetes]
            Alibaba_LB[SLB Load Balancer]
            Alibaba_Storage[OSS, EBS, NAS]
        end
        
        subgraph "Oracle Cloud Deployment"
            OCI_VCN[OCI VCN<br/>Subnets]
            OCI_K8s[OKE Cluster<br/>Kubernetes]
            OCI_LB[Load Balancer]
            OCI_Storage[Object Storage, Block Volume, File Storage]
        end
        
        subgraph "ByteDance Cloud Deployment"
            ByteDance_VPC[ByteDance VPC<br/>Subnets]
            ByteDance_K8s[TKE Cluster<br/>Kubernetes]
            ByteDance_LB[CLB Load Balancer]
            ByteDance_Storage[TOS, EBS, NAS]
        end
        
        subgraph "Huawei Cloud Deployment"
            Huawei_VPC[Huawei VPC<br/>Subnets]
            Huawei_K8s[CCE Cluster<br/>Kubernetes]
            Huawei_LB[ELB Load Balancer]
            Huawei_Storage[OBS, EVS, SFS]
        end
        
        subgraph "On-Premise Deployment"
            OnPrem_Network[Private Network<br/>VLANs/Subnets]
            OnPrem_K8s[Kubernetes Cluster<br/>Rancher/OpenShift/K3s]
            OnPrem_LB[Load Balancer<br/>HAProxy/Nginx]
            OnPrem_Storage[Local Storage<br/>NFS/Ceph/GlusterFS]
        end
    end
    
    subgraph "Common Components"
        VPN[VPN Gateway<br/>Site-to-Site]
        Monitoring[Observability Stack<br/>Mimir, Loki, Tempo]
        Cache[Cache Layer<br/>Redis/Valkey]
    end
    
    AWS_K8s --> AWS_LB
    GCP_K8s --> GCP_LB
    Azure_K8s --> Azure_LB
    Alibaba_K8s --> Alibaba_LB
    OCI_K8s --> OCI_LB
    ByteDance_K8s --> ByteDance_LB
    Huawei_K8s --> Huawei_LB
    OnPrem_K8s --> OnPrem_LB
    
    AWS_K8s --> AWS_Storage
    GCP_K8s --> GCP_Storage
    Azure_K8s --> Azure_Storage
    Alibaba_K8s --> Alibaba_Storage
    OCI_K8s --> OCI_Storage
    ByteDance_K8s --> ByteDance_Storage
    Huawei_K8s --> Huawei_Storage
    OnPrem_K8s --> OnPrem_Storage
    
    AWS_K8s --> VPN
    GCP_K8s --> VPN
    Azure_K8s --> VPN
    Alibaba_K8s --> VPN
    OCI_K8s --> VPN
    ByteDance_K8s --> VPN
    Huawei_K8s --> VPN
    OnPrem_K8s --> VPN
    
    AWS_K8s --> Monitoring
    GCP_K8s --> Monitoring
    Azure_K8s --> Monitoring
    Alibaba_K8s --> Monitoring
    OCI_K8s --> Monitoring
    ByteDance_K8s --> Monitoring
    Huawei_K8s --> Monitoring
    OnPrem_K8s --> Monitoring
    
    AWS_K8s --> Cache
    GCP_K8s --> Cache
    Azure_K8s --> Cache
    Alibaba_K8s --> Cache
    OCI_K8s --> Cache
    ByteDance_K8s --> Cache
    Huawei_K8s --> Cache
    OnPrem_K8s --> Cache